### ISSUE TITLE
Don't use docker binary for push & run

### ISSUE THREAD

**Issue by zroubalik** [boson-project/func#179]
Currently we are using `docker` binary for running `push` and `run`: https://github.com/boson-project/faas/blob/f4851fb669462ab348b9f51f60b813ef1494f9b5/docker/pusher.go#L28

We should use some library for this, Docker Go SDK is not ideal, because with this library it is [quite hard to do authentication ](https://github.com/moby/moby/issues/39377#issuecomment-503589708). But there should be another options as well.

**Comment by zroubalik** [comment]
this might be useful: https://github.com/containers/image

**Comment by lance** [comment]
Oh wow - I had been thinking that we were using the libs. Hrmm.
