### ISSUE TITLE
Quarkus build fail results in extraneous error reporting

### ISSUE THREAD

**Issue by utherp0** [boson-project/func#255]
When the compilation of a Quarkus function fails the returned information seems to be excessively full of [builder] tags (one for every character in the return error messages.
<img width="1387" alt="Screenshot 2021-01-29 at 09 42 37" src="https://user-images.githubusercontent.com/2233236/106282522-9d332f00-6238-11eb-856b-53ea2dbf81ef.png">

**Comment by matejvasek** [comment]
Might be issue of pack dependency, https://github.com/buildpacks/pack/pull/867.
