### ISSUE TITLE
Support deploying without implicitly building

### ISSUE THREAD

**Issue by lkingland** [boson-project/func#272]
Currently, the deploy step (both CLI and client library) implicitly build.

This default behavior should be updated such that the client library _either_ builds or deploys, depending on the `Client` method invoked, and the `func` CLI's `deploy` subcommand updated to invoke Build by default, which can be disabled via flag.

Errors will be expected when attempting to deploy an unbuilt Function.  This potentially may require the inclusion of an explicit --image flag to force completion, which should probably also update the Function's func.yaml if provided.

**Comment by lance** [comment]
Fixed in https://github.com/boson-project/func/pull/279
