### ISSUE TITLE
upgrade to go:embed for templates

### ISSUE THREAD

**Issue by lkingland** [boson-project/func#275]
With the release of Go 1.16, the ability to embed static files is now included as the `go:embed` directive.  This should be used in leau of the current `pkger` third-party dependency, as this will both greatly improve the intuitiveness with which updates to templates will be included, as well as simplify our overall build and release tooling.

**Comment by lkingland** [comment]
One side-effect of this update will be the loss of custom file modes on *nix-y systems.
https://golang.org/src/embed/embed.go?s=5559:6576#L235
As a side-effect of the decision that the embedded filesystem be an expressly read-only FS, the Mode permisions are hard-coded.
This means embedding things like setup scripts in templates will require manual intervention to change permisson to executable.

**Comment by lance** [comment]
> This means embedding things like setup scripts in templates will require manual intervention to change permisson to executable.

Bummer

**Comment by matejvasek** [comment]
What if we embed tar files, they should preserve *nix rights?

**Comment by lkingland** [comment]
Thats a good idea. IIRC the tar archive implements the fs.FS interface, so we should be able to use it directly. I'll refactor and give that a shot.

**Comment by lance** [comment]
> Thats a good idea. IIRC the tar archive implements the fs.FS interface, so we should be able to use it directly. I'll refactor and give that a shot.
