### ISSUE TITLE
Binaries created in CI do not have the proper version

### ISSUE THREAD

**Issue by lance** [boson-project/func#277]
The [latest release](https://github.com/boson-project/func/releases/tag/v0.11.0) still says `v0.0.0`.

```
~/Downloads via 🐹 v1.14.9
❯ ./func_linux_amd64 --version
v0.0.0
```

I think this may be resolved when run as a `kn` plugin, because `SetMeta` is being called with explicit values here.

https://github.com/boson-project/func/blob/8143ea1056626b238c40010fb0ede3bdc5fb5065/plugin/plugin.go#L28

But, when running in CI, it's expecting a git tag on the current commit hash.

https://github.com/boson-project/func/blob/8143ea1056626b238c40010fb0ede3bdc5fb5065/Makefile#L11-L14

I'm not sure what's going on exactly. The `release-please` task runs before the build, but as you can see from this build of `v0.11.0` the Makefile thinks it's `tip`. 

https://github.com/boson-project/func/runs/1743466022?check_suite_focus=true#step:6:43

**Comment by lkingland** [comment]
Since I am in there poking about in our CI tasks, I can take a look here.  My guess is a loose wire somewhere; this should work fine so long as we're building via the Makefile target.

**Comment by lance** [comment]
Assuming [this works](https://github.com/boson-project/func/pull/290) in our next release, this can be closed. Will reopen if needed.
