### ISSUE TITLE
Add spinner/progress bar to 'build' and 'deploy'

### ISSUE THREAD

**Issue by lance** [boson-project/func#296]
Running `kn func build` can take a while, and there is no user feedback to let them know that things are progressing. A "progress bar" was originally requested. However, unless there is some callback/event mechanism in the `pack` API that would allow us to determine progress, this will probably just need to be a spinner of some kind.

**Comment by matejvasek** [comment]
IIRC there used to be spinner in older versions, am I right @lkingland

**Comment by nainaz** [comment]
There was a spinner. 
"Progress bar" --> way to inform that it is woking. 
Open to all suggestions on how it could be shown.

**Comment by lkingland** [comment]
Yes, there was a spinner with a progress indicator (not a visualized bar) with major steps "2/4 Building" etc.  which showed both activity and progress at a coarse level.

This is however limited to the major steps exposed by our API, and treats the build step as a single (very large) step.  As Lance says, unless Pack has a progress registration callback mechanism we may have to settle on a spinner for now.  At least this will indicate that, as Naina mentions, _something_ is happening and the process is not hung.
