### ISSUE TITLE
Allow for annotations in func.yaml

### ISSUE THREAD

**Issue by lance** [boson-project/func#307]
From Burr:

> I love these 2 annotations for my Knative demos, what is the way with func.yaml?
```
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/window: 16s
```
> The first is related to concurrency,the 2nd is the scale-down-to-zero interval

Related: https://github.com/boson-project/func/issues/261

**Comment by zroubalik** [comment]
Related: https://github.com/boson-project/func/issues/164

**Comment by lance** [comment]
I started implementing this today and it was quite simple. Adding annotations like `foo: bar` is trivial - whether when creating a new function or updating an existing one. However, `autoscaling.knative.dev/*` produces this:

```console
❯ kn func deploy
Building function image
Function image has been built, image: docker.io/lanceball/foo:latest
Pushing function image to the registry
Deploying function to the cluster
Error: knative deployer failed to deploy the service: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: invalid key name "autoscaling.knative.dev/target": metadata.annotations
autoscaling annotations must be put under "spec.template.metadata.annotations" to work
invalid key name "autoscaling.knative.dev/window": metadata.annotations
autoscaling annotations must be put under "spec.template.metadata.annotations" to work
Error: exit status 1
```

So for these kinds of annotations, we should approach it as `kn` does, with explicit flags or configuration values.

```console
--autoscale-window string           Duration to look back for making auto-scaling decisions. The service is scaled to zero if no request was received in during that time. (eg: 10s)
```
So, in `func`, to set the `autoscaling.knative.dev/window|target` annotations, we should consider adding something like this to func.yaml and use `kn` client APIs to set them. I can't find a reference to the autoscaling target in the `kn` docs, however, but I may just not know where to look.

```yaml
autoscale:
  window: 16s,
  target: 1
```
@rhuss is it possible to set the autoscaling target in the `kn` CLI?

**Comment by rhuss** [comment]
Yes, auotscaling parameters can be set/updated with `kn`:

```
      --autoscale-window string           Duration to look back for making auto-scaling decisions. The service is scaled to zero if no request was
                                          received in during that time. (eg: 10s)
      --concurrency-limit int             Hard Limit of concurrent requests to be processed by a single replica.
      --concurrency-target int            Recommendation for when to scale up based on the concurrent number of incoming request. Defaults to
                                          --concurrency-limit when given.
      --concurrency-utilization int       Percentage of concurrent requests utilization before scaling up. (default 70)
      --scale-init int                    Initial number of replicas with which a service starts. Can be 0 or a positive integer.
      --scale-max int                     Maximum number of replicas.
      --scale-min int                     Minimum number of replicas.
```

**Comment by zroubalik** [comment]
My original idea was to allow setting arbitrary `kn` parameters (that are relevant to `KService`) in `func.yaml`, eg:
```yaml
knFlags:
  autoscale-window: 10 
  concurrency-limit: 5
...
```
Tthese flags (not just autoscaling) would be then used when creating/updating a KService via kn client API.  If we do it right, we can support all flags that `kn` provides and will provide in future. @rhuss is there a way in kn client API to set this kind of flags?

Doing this through annotation is interesting approach as well and maybe better?

**Comment by rhuss** [comment]
These flags translate to either fields in the KService spec or to annotations and are populated before the call to the API affair. So there is probably no direct support for those and also no generic way yet how to map CLI option to updating a KService CR (however, this would be probably a good idea to make this more generic)

**Comment by lance** [comment]
> Yes, auotscaling parameters can be set/updated with `kn`:

@rhuss I was specifically wondering about `autoscaling.knative.dev/target` which does not seem to be something I can change with `kn`. Am I missing it somewhere?

**Comment by rhuss** [comment]
> @rhuss I was specifically wondering about autoscaling.knative.dev/target which does not seem to be something I can change with kn. Am I missing it somewhere?

This annotation is set/updated with `--concurrency-target`
