### ISSUE TITLE
A non-default builder in func.yaml is overwritten by 'kn func build'

### ISSUE THREAD

**Issue by lance** [boson-project/func#308]
If I run `kn func build -b native` on a quarkus function, the build actually uses the native builder image, and updates `func.yaml` to reflect this. But if I subsequently run `kn func build` without the `-b native` flag, the customized value for `builder` is overwritten with the default builder image, and the default builder image is used.

Steps to reproduce this:

```
❯ kn func build -b native
...

❯ grep builder func.yaml
builder: native
builderMap:
  default: quay.io/boson/faas-quarkus-jvm-builder
  jvm: quay.io/boson/faas-quarkus-jvm-builder
  native: quay.io/boson/faas-quarkus-native-builder

❯ kn func build
...

❯ grep builder func.yaml
builder: default
builderMap:
  default: quay.io/boson/faas-quarkus-jvm-builder
  jvm: quay.io/boson/faas-quarkus-jvm-builder
  native: quay.io/boson/faas-quarkus-native-builder
```

**Comment by matejvasek** [comment]
@lance I'll look at this.
