### ISSUE TITLE
Provide a new emit command to send events

### ISSUE THREAD

**Issue by lance** [boson-project/func#331]
For local development, it would be nice if I could send simulated events to my function. I should be able to specify the source, type and optionally the data. I should be able to send the event to the deployed URL for my function, or to localhost. I propose the following interface.

```console
func emit [--source="/some/source"] [--type="some.type"] [--id=someid] [--data=./path/to/json] [--local]
```
All flags are optional.

**Comment by zroubalik** [comment]
Done in https://github.com/boson-project/func/pull/332
